 INSERT INTO marks (mark) VALUES('Mercedes-Benz'),
    ('BMW'),
    ('Honda'),
    ('Kia'),
    ('Toyota'),
    ('Aston Martin'),
    ('Alfa Romeo'),
    ('Citroen'),
    ('Bentley'),
    ('Ferrari'),
    ('Ford'),
    ('Peugeot'),
    ('Volkswagen'),
    ('Volvo'),
    ('Seat');